// Section copy. Order defines scroll order and camera waypoints.
// `accent` words are pulled out for italic display treatment.
export const sections = [
  {
    id: 'hero',
    index: null,
    kicker: 'Portfolio — 2026',
    title: 'Prathvi',
    accent: null,
    lead: 'Editor · Motion · Graphic · Web · Brand',
    body: 'Five disciplines, one pair of hands.',
  },
  {
    id: 'about',
    index: '01',
    kicker: 'About',
    title: 'One craft,',
    accent: 'five disciplines',
    body: 'Most projects get handed to five specialists and come back sounding like five people. I take it end to end — the cut, the motion, the type, the build, the brand around it — so it arrives in one voice.',
    stat: ['5', 'disciplines'],
  },
  {
    id: 'editing',
    index: '02',
    kicker: 'Editing',
    title: 'Rhythm is',
    accent: 'everything',
    body: 'Long-form, short-form, documentary, commercial. Finding the cut that earns attention in two seconds and holds it to the last frame.',
    meta: ['Premiere Pro', 'DaVinci Resolve', 'Colour', 'Sound Design'],
  },
  {
    id: 'motion',
    index: '03',
    kicker: 'Motion Design',
    title: 'Making stills',
    accent: 'breathe',
    body: 'Title sequences, explainers, product reveals, broadcast packages. Motion that carries meaning rather than decorating it.',
    meta: ['After Effects', 'Cinema 4D', 'Blender', 'Rigging'],
  },
  {
    id: 'graphic',
    index: '04',
    kicker: 'Graphic Design',
    title: 'Type, grid,',
    accent: 'restraint',
    body: 'Identity systems, posters, packaging, editorial layout. Composition that survives being printed, posted, and scaled to a favicon.',
    meta: ['Illustrator', 'Photoshop', 'Figma', 'InDesign'],
  },
  {
    id: 'web',
    index: '05',
    kicker: 'Web Development',
    title: 'Designed and',
    accent: 'shipped',
    body: 'Sites that behave as well as they look — accessible, quick on real networks, maintainable after launch. This page is one: a procedural forest, instanced grass, and a camera on a spline.',
    meta: ['React', 'Three.js', 'R3F', 'GLSL', 'Vite'],
  },
  {
    id: 'brand',
    index: '06',
    kicker: 'Brand Management',
    title: 'The system',
    accent: 'behind it',
    body: 'Positioning, guidelines, content calendars, and the discipline to keep a brand recognisable across every surface it lands on.',
    meta: ['Strategy', 'Guidelines', 'Campaigns', 'Direction'],
  },
  {
    id: 'contact',
    index: '07',
    kicker: 'Contact',
    title: "Let's make",
    accent: 'something',
    body: 'Open to freelance projects, retainers and collaborations.',
    email: 'hello@prathvi.design',
    socials: [
      ['Instagram', 'https://instagram.com'],
      ['Behance', 'https://behance.net'],
      ['LinkedIn', 'https://linkedin.com'],
    ],
  },
];
